export const CMS_API: string = "/api";
export const CMS_PRODUCTS: string = "/products";
export const CMS_NOTIFICATIONS: string = "/notifications";
export const CMS_CATEGORIES: string = "/categories";
export const CMS_LAST_CHANGES: string = "/lastchanges";
export const CMS_UPLOAD: string = "/upload";
export const CMS_PRODUCTS_REF: string = "api::product.product";
export const IMAGE_FIELD: string = "image";
export const POPULATE_ALL: string = "?populate=*";
export const FILTERS: string = "filters";
export const NOTIFICATION_ADDRESS: string = "address";
export const OWNER_ADDRESS: string = "ownerAddress";
export const EQUALS: string = "$eq";
export const DEFAULT_RAISED_AMOUNT = 0;
